USE DATABASE SMOOTHIES;

CREATE TABLE IF NOT EXISTS RAW.FRUIT_NUTRITION (
    FRUIT_NAME VARCHAR NOT NULL,
    CALORIES NUMBER(10,2),
    SUGAR_G NUMBER(10,2),
    CARBOHYDRATES_G NUMBER(10,2),
    PROTEIN_G NUMBER(10,2),
    FAT_G NUMBER(10,2),
    SOURCE_API VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS CURATED.SMOOTHIE_ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT,
    CUSTOMER_NAME VARCHAR NOT NULL,
    INGREDIENTS VARCHAR NOT NULL,
    ORDERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SMOOTHIE_ORDERS PRIMARY KEY (ORDER_ID)
);


CREATE TABLE IF NOT EXISTS CURATED.SMOOTHIE_NUTRITION (
    ORDER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    TOTAL_CALORIES NUMBER(10,2),
    TOTAL_SUGAR_G NUMBER(10,2),
    TOTAL_CARBOHYDRATES_G NUMBER(10,2),
    TOTAL_PROTEIN_G NUMBER(10,2),
    TOTAL_FAT_G NUMBER(10,2),
    CALCULATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);