USE DATABASE SMOOTHIES;


CREATE OR REPLACE VIEW ANALYTICS.DAILY_ORDER_VOLUME AS
SELECT
    CAST(ORDERED_AT AS DATE) AS ORDER_DATE,
    COUNT(*) AS ORDER_COUNT
FROM CURATED.SMOOTHIE_ORDERS
GROUP BY CAST(ORDERED_AT AS DATE)
ORDER BY ORDER_DATE;


CREATE OR REPLACE VIEW ANALYTICS.POPULAR_INGREDIENTS AS
SELECT
    TRIM(value::STRING) AS INGREDIENT,
    COUNT(*) AS USAGE_COUNT
FROM CURATED.SMOOTHIE_ORDERS,
LATERAL FLATTEN(
    INPUT => SPLIT(INGREDIENTS, ',')
)
GROUP BY TRIM(value::STRING)
ORDER BY USAGE_COUNT DESC;


CREATE OR REPLACE VIEW ANALYTICS.ORDER_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_NAME) AS UNIQUE_CUSTOMERS,
    MIN(ORDERED_AT) AS FIRST_ORDER,
    MAX(ORDERED_AT) AS LAST_ORDER
FROM CURATED.SMOOTHIE_ORDERS;