USE DATABASE SMOOTHIES;


-- Orders missing customer names
SELECT COUNT(*) AS INVALID_CUSTOMER_NAMES
FROM CURATED.SMOOTHIE_ORDERS
WHERE CUSTOMER_NAME IS NULL
   OR TRIM(CUSTOMER_NAME) = '';


-- Orders missing ingredients
SELECT COUNT(*) AS INVALID_INGREDIENTS
FROM CURATED.SMOOTHIE_ORDERS
WHERE INGREDIENTS IS NULL
   OR TRIM(INGREDIENTS) = '';


-- Nutrition records with negative calories
SELECT COUNT(*) AS INVALID_CALORIES
FROM CURATED.SMOOTHIE_NUTRITION
WHERE TOTAL_CALORIES < 0;


-- Nutrition records with negative sugar
SELECT COUNT(*) AS INVALID_SUGAR
FROM CURATED.SMOOTHIE_NUTRITION
WHERE TOTAL_SUGAR_G < 0;